#pragma once

#include "../numericTypes/types.h"
#include "../numericTypes/index.h"
#include <cmath>
#include <cstdint>
namespace Config
{
	//inline int medicalPriority;
	//inline int medicalProjectDelaySteps;
	//
	// sort command for vim:
	// 	sort /\t/w* /w* /w* /
	inline constexpr int actorDoVisionInterval = 3;
	inline constexpr int bytesPerCacheLine = 64;
	inline constexpr bool fluidPiston = false;
	inline constexpr float dataStoreVectorResizeFactor = 1.5;
	inline constexpr float dataStoreVectorInitalSize = 10;
	inline constexpr float goldenRatio = 1.61834f;
	inline constexpr int maxActorsPerPoint = 4;
	inline constexpr int maxItemsPerPoint = 4;
	inline constexpr Distance maxDepthExteriorPortalPenetration = Distance::create(6);
	inline constexpr int rtreeNodeSize = {64};
	inline constexpr std::size_t soldiersPerMoraleCheckThread = 64;
	inline constexpr bool validateFluidTotals = false;

	// sort command for vim:
	// 	sort /\t/w* /w* /
	inline int accidentalHitLargestArea;
	inline int accidentalHitSmallestArea;
	inline Step addToStockPileDelaySteps;
	inline float adjacentAllyCombatScoreBonusModifier;
	inline int attackCoolDownDurationBaseDextarity;
	inline Step attackCoolDownDurationBaseSteps;
	inline float attackSkillCombatModifier;
	inline Quality averageItemQuality;
	inline size_t averageLandHeight;
	inline float averageNumberOfRiversPerCandidate;
	inline Step baseHealDelaySteps;
	inline MoveCost baseMoveCost;
	inline Step bleedEventBaseFrequency;
	inline Step bleedPassOutDuration;
	inline float bleedToDeathRatio;
	inline float bleedToUnconciousessRatio;
	inline float pointsPerMeter;
	inline int bludgeonBleedVoumeRateModifier;
	inline int bludgeonPercentPermanantImparmentModifier;
	inline int bludgeonPercentTemporaryImparmentModifier;
	inline int bludgeonStepsTillHealedModifier;
	inline float bodyHardnessModifier;
	inline float chastiseCastingCallBonusForDefenderIsFamily;
	inline float chastiseCastingCallBonusForDefenderIsFriend;
	inline float chastiseCastingCallDefenderMinimumScore;
	inline float chanceToWaitInsteadOfWander;
	inline Step confrontationObjectiveTempoSteps;
	inline Priority constructObjectivePriority;
	inline float constructSkillModifier;
	inline float constructStrengthModifier;
	inline Priority craftObjectivePriority;
	inline int cutBleedVoumeRateModifier;
	inline int cutPercentPermanantImparmentModifier;
	inline int cutPercentTemporaryImparmentModifier;
	inline int cutStepsTillHealedModifier;
	inline int daysPerYear;
	inline Temperature deepAmbiantTemperature;
	inline Step dialogLineDefaultDurationSteps;
	inline Step digMaxSteps;
	inline Priority digObjectivePriority;
	inline float digSkillModifier;
	inline float digStrengthModifier;
	inline Priority drinkPriority;
	inline Priority eatPriority;
	inline Energy energyGeneratedByOneUnitMassFallingOneDistance;
	inline Priority equipPriority;
	inline Step exterminateCheckFrequency;
	inline Priority exterminatePriority;
	inline float fatPierceForceCost;
	inline float fireRampDownPhaseDurationFraction;
	inline float flankingModifier;
	inline Priority fleePriority;
	inline float fluidDragModifier;
	inline int fluidGroupsPerThread;
	inline float forceAbsorbedPiercedModifier;
	inline float forceAbsorbedUnpiercedModifier;
	inline float fractionAttackCoolDownReductionPerPointOfDextarity;
	inline float fractionOfMoveSpeedToMakeDistanceHuristicForCanMoveToSoon;
	inline int getIntoAttackPositionMaxRange;
	inline Priority getToSafeTemperaturePriority;
	inline Step givePlantsFluidDelaySteps;
	inline Priority givePlantsFluidPriority;
	inline Priority goToPriority;
	inline MoveCost goUpMoveCost;
	inline Step harvestEventDuration;
	inline Priority harvestPriority;
	inline float heatDisipatesAtDistanceExponent;
	inline float heatFractionForBurn;
	inline float heatFractionForSmoulder;
	inline Distance heatDistanceMaximum;
	inline TemperatureDelta heatRadianceMinimum;
	inline int hitAreaToBodyPartVolumeRatioForFatalStrikeToVitalArea;
	inline int hitScaleModifier;
	inline int hitsToDivideActorFallDamageInto;
	inline int hoursPerDay;
	inline FullDisplacement impassibleItemVolume;
	inline Step installItemDuration;
	inline Priority installItemPriority;
	inline float itemQualityCombatModifier;
	inline float itemQualityModifier;
	inline float itemSkillModifier;
	inline float itemTypeCombatModifier;
	inline float itemTypeCombatScoreModifier;
	inline float itemWearCombatModifier;
	inline float itemWearModifier;
	inline Priority killPriority;
	inline int lakeDepthModifier;
	inline int lakeRadiusModifier;
	inline Step loadDelaySteps;
	inline float massCarryMaximimMovementRatio;
	inline int maxAnimalInsertLocationSearchRetries;
	inline Distance maxChastiseDistance;
	inline CollisionVolume maxPointVolume;
	inline Distance maxPointsToLookForBetterFood;
	inline Distance maxDistanceToLookForEatingLocation;
	inline float maxDistanceVisionModifier;
	inline Quantity maxNumberOfWorkersForConstructionProject;
	inline Quantity maxNumberOfWorkersForDigProject;
	inline Quantity maxNumberOfWorkersForWoodCuttingProject;
	inline Distance maxRangeToSearchForCraftingRequirements;
	inline Distance maxRangeToSearchForStockPileItems;
	inline Distance maxRangeToSearchForStockPiles;
	inline Distance maxRangeToSearchForDigDesignations;
	inline Distance maxRangeToSearchForConstructionDesignations;
	inline Distance maxRangeToSearchForWoodCuttingDesignations;
	inline Distance maxRangeToSearchForHorticultureDesignations;
	inline Distance maxRangeToSearchForUniformEquipment;
	inline int maxSizeOfLongRangePathNode;
	inline int maxSkillLevel;
	inline Stamina maxStaminaPointsBase;
	inline Quantity maxWorkersForStockPileProject;
	inline Distance maxZLevelForDeepAmbiantTemperature;
	inline PsycologyWeight maximumDeltaToAlterPsycologyCurrentSquared;
	inline Step maximumDurationToWaitInsteadOfWander;
	inline float maximumForceRatioToMassForNonLethalAttack;
	inline float maximumRainIntensityModifier;
	inline float maximumRatioOfBloodRemainingForSeriousInjury;
	inline Step maximumStepsBetweenRainPerPercentHumidity;
	inline Step maximumStepsRainPerPercentHumidity;
	inline Meters metersHeightCarvedByRivers;
	inline Meters metersPerUnitElevationLociiIntensity;
	inline Meters minimumAltitudeForHeadwaterFormation;
	inline float minimumAttackCoolDownModifier;
	inline float minimumCombatScoreDifferenceToFeelFear;
	inline PsycologyWeight minimumDeltaToAlterPsycologyBaselineSquared;
	inline Step minimumDurationToWaitInsteadOfWander;
	inline Speed minimumHaulSpeedInital;
	inline Percent minimumImpairPercentForSeriousInjury;
	inline float minimumOverloadRatio;
	inline Percent minimumPercentFoliageForGrow;
	inline Percent minimumPercentGrowthForWoodCutting;
	inline float minimumRainIntensityModifier;
	inline float minimumRatioAdjacentSpaceContainingFluidToFloat;
	inline CollisionVolume minPointStaticVolumeToSlowMovement;
	inline Step minimumStepsBetweenRainPerPercentHumidity;
	inline Step minimumStepsRainPerPercentHumidity;
	inline int minimumSizeForOctTreeToSplit;
	inline int minimumOccupantsForOctTreeToSplit;
	inline int maximumOccupantsForOctTreeToMerge;
	inline int minimumSizeOfGroupOfMovingPointsWhichSkipLineOfSightChecksForMakingVisionRequests;
	inline CollisionVolume minimumVolumeOfFluidToBreath;
	inline int minutesPerHour;
	inline int moveTryAttemptsBeforeDetour;
	inline float modifierToTurnMassTimesFallDistanceIntoForce;
	inline float musclePierceForceCost;
	inline int octTreeSortEntropyThreshold;
	//TODO: is this a duplicate?
	inline Priority objectivePrioiorityKill;
	inline Priority objectivePrioritySleep;
	inline PsycologyWeight painWhenALimbIsSevered;
	inline int pathRequestsPerThread;
	inline float pathHuristicConstant;
	inline Percent percentHeightCarvedByRivers;
	// How hungry does an actor have to be to cross a hunger threshold and be willing to eat something less desirable?
	inline std::array<int, 3> minimumHungerLevelThresholds;
	inline Percent percentOfPlantMassWhichIsFoliage;
	inline Percent percentPermanantImparmentMinimum;
	inline int pierceBleedVoumeRateModifier;
	inline float pierceBoneModifier;
	inline float pierceFatModifier;
	inline float pierceModifier;
	inline float pierceMuscelModifier;
	inline int piercePercentPermanantImparmentModifier;
	inline int piercePercentTemporaryImparmentModifier;
	inline float pierceSkinModifier;
	inline int pierceStepsTillHealedModifier;
	inline int plantSortEntropyThreashold;
	inline float pointsOfCombatScorePerUnitOfAgility;
	inline float pointsOfCombatScorePerUnitOfDextarity;
	inline float pointsOfCombatScorePerUnitOfStrength;
	inline int projectTryToMakeSubprojectRetriesBeforeProjectDelay;
	inline Step projectDelayAfterExauhstingSubprojectRetries;
	inline int projectileHitChanceFallsOffWithRangeExponent;
	inline float projectileHitPercentPerPointAttackTypeCombatScore;
	inline float projectileHitPercentPerPointDextarity;
	inline float projectileHitPercentPerPointQuality;
	inline float projectileHitPercentPerPointTargetCombatScore;
	inline float projectileHitPercentPerPointWear;
	inline float projectileHitPercentPerSkillPoint;
	inline float projectileHitPercentPerUnitVolume;
	inline FullDisplacement projectileMedianTargetVolume;
	inline Distance rainMaximumOffset;
	inline Distance rainMaximumSpacing;
	inline Step rainWriteStepFreqency;
	inline float rateModifierForEvaporationPerDegreeTemperature;
	inline float ratioOfHitAreaToBodyPartVolumeForSever;
	inline float ratioOfMaximumVarianceForCourageTest;
	inline float ratioOfTotalBodyVolumeWhichIsBlood;
	inline float ratioWoundsCloseDelayToBleedVolume;
	inline Step restIntervalSteps;
	inline float rollingMassModifier;
	inline float floatingMassModifier;
	inline float rowForcePerUnitStrength;
	inline int scaleOfHumanBody;
	inline int secondsPerMinute;
	inline float skinPierceForceCost;
	inline SkillExperiencePoints skillPointsToAddWhenChastised;
	inline SkillExperiencePoints skillPointsToAddWhenChastising;
	inline SkillExperiencePoints skillPointsToAddWhenSuccessAtWork;
	inline Priority sleepObjectivePriority;
	inline Priority sowSeedsPriority;
	inline Step sowSeedsStepsDuration;
	inline int staminaPointsPerRestPeriod;
	inline Priority stationPriority;
	inline Step stepsFrequencyToLookForHaulSubprojects;
	inline Step stepsFrequencyToRunRelationshipEvent;
	inline Step stepsPerDay;
	inline Step stepsPerHour;
	inline Step stepsPerMinute;
	inline Step stepsPerSecond;
	inline Step stepsPerYear;
	inline Step stepsPerUnitFluidVolumeGivenToPlant;
	inline Step stepsTillDiePlantPriorityOveride;
	inline Step stepsToDelayBeforeTryingAgainToCompleteAnObjective;
	inline Step stepsToDelayBeforeTryingAgainToFollowLeader;
	inline Step stepsToDelayBeforeTryingAgainToReserveItemsAndActorsForAProject;
	inline Step stepsToDisableStockPile;
	inline Step stepsToDrink;
	inline Step stepsToEat;
	inline Priority stockPilePriority;
	inline Priority targetedHaulPriority;
	inline int threadedTaskBatchSize;
	inline int unarmedCombatScoreBase;
	inline float unarmedCombatSkillModifier;
	inline Temperature undergroundAmbiantTemperature;
	inline int unitsBodyMassPerUnitFluidConsumed;
	inline Mass unitsBodyMassPerUnitFoodConsumed;
	inline float unitsOfAttackForcePerUnitOfStrength;
	inline float unitsOfCarryMassPerUnitOfStrength;
	inline float unitsOfMoveSpeedPerUnitOfAgility;
	inline int unitsOfWoundAreaPerUnitItemScaleFactor;
	inline float unitsOfVolumePerUnitOfCollisionVolume;
	inline float vehicleMassToCarryMassModifier;
	inline size_t visionRequestsReservationSize;
	inline int visionThreadingBatchSize;
	inline int wanderMaximumNumberOfPoints;
	inline int wanderMinimimNumberOfPoints;
	inline Step woodCuttingMaxSteps;
	inline Priority woodCuttingObjectivePriority;
	inline float woodCuttingSkillModifier;
	inline float woodCuttingStrengthModifier;
	inline Step yokeDelaySteps;

	inline int convertBodyPartVolumeToArea(FullDisplacement volume){ return sqrt(volume.get()); }
	void load();
}
