max-width 1025
max-height 1024
power-of-two true
colorkey
crop
crop-pivot

output "build/sheet{0-}.png"
description "build/sheet.json"

pivot center middle

input "source/sprites.png"
  grid 32 32
    sprite "roughFloor"
    sprite "roughWallSouth"
    sprite "roughWallWest"
    sprite "roughWallCorner"
    sprite "blockFloor"
    sprite "blockWallSouth"
    sprite "blockWallWest"
    sprite "blockWallCorner"
    sprite "grass"
    sprite "bush"
    sprite "tree1"
    sprite "tree2"
    sprite "pixel"
      extrude 4 clamp
  row 1
    sprite "sleep"
    sprite "hand"
    sprite "open"
    sprite "trunk"
    sprite "trunkWithBranches"
    sprite "trunkLeaves"
    sprite "branch"
    sprite "branchLeaves"
  row 2
    sprite "fluidSurface"

input "source/features.png"
  grid 32 32
    sprite "door"
    sprite "flap"
    sprite "hatch"
    sprite "stairs"
    sprite "ramp"
    sprite "floorGrate"
    sprite "floodGate"
    sprite "fortification"

input "source/animals.png"
  grid 32 32
    sprite "bear"
    sprite "fish"
    sprite "deer"
    sprite "equine"
    sprite "raptor"
    sprite "rabbit"
    sprite "fox"

input "source/sentient.png"
  grid 32 32
    sprite "goblin"
    sprite "dwarf"
    sprite "troll"

input "source/items.png"
  grid 32 32
    sprite "axe"
    sprite "fruit"
    sprite "bar"
    sprite "block"
    sprite "board"
    sprite "rock"
    sprite "bucket"
    sprite "tool"
    sprite "cart"
    sprite "arrow"
    sprite "crossbow"
    sprite "dagger"
    sprite "pile"
    sprite "log"
    sprite "sword"
    sprite "panniers"
  row 1
    sprite "cloths"
    sprite "peg"
    sprite "meal"
    sprite "rope"
    sprite "seed"
    sprite "pick"
    sprite "mallet"
    sprite "branch"
    sprite "greaves"
    sprite "chain mail shirt"
    sprite "shield"
    sprite "half helm"
    sprite "full helm"
    sprite "breast plate"
    sprite "mace"
    sprite "spear"
  row 2
    sprite "glave"
    sprite "bow"
  row 3
    sprite
    sprite
input "source/font_32.png"
  grid 32 32

    sprite "a"
    sprite "b"
    sprite "c"
    sprite "d"
    sprite "e"
    sprite "f"
    sprite "g"
    sprite "h"
    sprite "i"
    sprite "j"
    sprite "k"
    sprite "l"
    sprite "m"
    sprite "n"
    sprite "o"
    sprite "p"

  row 1
    sprite "q"
    sprite "r"
    sprite "s"
    sprite "t"
    sprite "u"
    sprite "v"
    sprite "w"
    sprite "x"
    sprite "y"
    sprite "z"
    sprite "A"
    sprite "B"
    sprite "C"
    sprite "D"
    sprite "E"
    sprite "F"

  row 2
    sprite "G"
    sprite "H"
    sprite "I"
    sprite "J"
    sprite "K"
    sprite "L"
    sprite "M"
    sprite "N"
    sprite "O"
    sprite "P"
    sprite "Q"
    sprite "R"
    sprite "S"
    sprite "T"
    sprite "U"
    sprite "V"

  row 3
    sprite "W"
    sprite "X"
    sprite "Y"
    sprite "Z"
    sprite "0"
    sprite "1"
    sprite "2"
    sprite "3"
    sprite "4"
    sprite "5"
    sprite "6"
    sprite "7"
    sprite "8"
    sprite "9"
